"""create_board_states_table

Revision ID: e05012157e9c
Revises: 
Create Date: 2023-08-30 18:40:14.701776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05012157e9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_state', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_states_id'), 'board_states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_states_id'), table_name='board_states')
    op.drop_table('board_states')
    # ### end Alembic commands ###
